In [1]:
import numpy as np

### Creating Arrays

In [4]:
zeros_array=np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [5]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
constant_array = np.full(10, 3)
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

### Converting Lists to Arrays

In [9]:
my_list = [2, 3, 4]
arr=np.array(my_list)
arr

array([2, 3, 4])

### Generating Ranges of Numbers

In [12]:
range_numbers=np.arange(10)
range_numbers

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays with Linear Spacing

In [13]:
line_space=np.linspace(0,1,11)
line_space

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimensional Arrays

In [15]:
zeros_matrix = np.zeros((2, 2))
zeros_matrix

array([[0., 0.],
       [0., 0.]])

In [17]:
constant_matrix = np.full((2, 2), 3)
constant_matrix

array([[3, 3],
       [3, 3]])

### Generating Random Arrays

In [32]:
np.random.seed(42)
random_array=np.random.rand(2,2)
random_array

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848]])

In [30]:
normal_distribution=np.random.randn(2,2)
normal_distribution

array([[0.56446424, 0.02550067],
       [0.47319325, 0.6591906 ]])

In [31]:
random_integers=np.random.randint(low=0,high=100,size=(2,2))
random_integers

array([[52, 23],
       [25, 88]])

### Array Operations

In [38]:
arr=np.ones((2,2))
arr+1

array([[2., 2.],
       [2., 2.]])

In [40]:
arr*4

array([[4., 4.],
       [4., 4.]])

### Comparison Operations

In [42]:
arr = np.array([1, 2, 3, 4])
greater_than_2 = arr > 2  # Produces [False, False, True, True]
greater_than_2

array([False, False,  True,  True])

### Selecting Elements Based on Conditions

In [43]:
greater_than_2 = arr[arr > 2]
greater_than_2

array([3, 4])

In [44]:
arr.min()

np.int64(1)

In [45]:
arr.max()

np.int64(4)

In [46]:
arr.sum()

np.int64(10)

In [47]:
arr.mean()

np.float64(2.5)

In [48]:
arr.std()

np.float64(1.118033988749895)