In [1]:
import numpy as np

### Vector operations

In [17]:
u = np.array([2, 4, 5, 6])
v = np.array([1, 0, 0, 2])

In [18]:
# addition 
u + v

array([3, 4, 5, 8])

In [19]:
# subtraction 
u - v

array([1, 4, 5, 4])

In [20]:
# scalar multiplication 
2 * v

array([2, 0, 0, 4])

### Multiplication

In [21]:
def vector_vector_multiplication(u,v):
    assert u.shape[0]==v.shape[0]

    n=u.shape[0]
    res=0
    for i in range(n):
        res=res+u[i]*v[i]
    return res

In [22]:
vector_vector_multiplication(u,v)

np.int64(14)

In [23]:
u.dot(v)

np.int64(14)

In [29]:
u = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1],
])

In [30]:
u.shape

(3, 4)

### Matrix-vector multiplication

In [33]:
def matrix_vector_multiplication(u,v):
    assert u.shape[1]==v.shape[0]
    num_rows=u.shape[0]
    res=np.zeros(num_rows)
    for i in range(num_rows):
        res[i]=vector_vector_multiplication(u[i],v)
    return res

In [34]:
matrix_vector_multiplication(u,v)

array([14.,  5.,  5.])

In [36]:
u.dot(v)

array([14,  5,  5])

### Identity matrix

In [38]:
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Inverse

In [43]:
vs=np.array([[1, 2, 3],
              [0, 1, 4],
              [5, 6, 0]])
vs

array([[1, 2, 3],
       [0, 1, 4],
       [5, 6, 0]])

In [44]:
vs_inv=np.linalg.inv(vs)
vs_inv

array([[-24.,  18.,   5.],
       [ 20., -15.,  -4.],
       [ -5.,   4.,   1.]])

In [46]:
vs_inv.dot(vs)

array([[ 1.0000000e+00,  0.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 0.0000000e+00, -8.8817842e-16,  1.0000000e+00]])